Vistech.Andon.Web/Controllers/WCController.cs
using System;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using ProAlert.Andon.Service.Interfaces;
using ProAlert.Andon.Service.Models;
using ProAlert.Andon.Service.ViewModels;
using Vistech.Andon.Web.Models;
using Vistech.Andon.Web.Tools;

namespace Vistech.Andon.Web.Controllers
{
    //[InitializeSimpleMembership]
    [Authorize(Roles = "Operator, Admin, Tech, Maint, Super")]
    public class WCController : Controller
    {
        //
        // GET: /WC/
        #region < Members >
        //private IRepository _repo;
        private OeeCache _cache;
        #endregion

        //public WCController(IRepository repo)
        //{
            
        //    _repo = repo;
        //    _cache = new OeeCache();
        //}
        public WCController()
        {
        }
        
        public ActionResult WCList()
        {
            using (var context = new ProAlertContext())
            {
                using (var repo = new EntityFrameworkRepository<ProAlertContext>(context))
                {
                    var query = (from wc in repo.GetAll<WorkCenter>()
                                 select wc).ToList();

                    return View(query);
                }
            }
        }

        public ActionResult AlreadyRunning()
        {
            return View();
        }
        public ActionResult WC(int id)
        {
            using (var db = new ProAlertContext())
            {
                using (var repo = new EntityFrameworkRepository<ProAlertContext>(db))
                {
                    var wc = repo.GetOne<WorkCenter>(x => x.Id == id, "WorkCenterGUIOptions");
                    if (wc.GuiRunning) RedirectToAction("AlreadyRunning");
                    // Not running yet... but, when we leave this method, we will be.. so set it.
                    wc.GuiRunning = true;
                    repo.Save();
                    // do we have a new work center? If tl is null, we do.

                    var tl = repo.GetOne<WCProductTimeline>(x => x.WorkCenterID == id && x.Current, "ShiftLog, ProductWCStatsHistory, Timesegments, WorkCenter, Product");
                    ProductTimelineStatsVM tlVm;
                    if (tl == null)
                    {
                        var now = DateTime.UtcNow;

                        tlVm = new ProductTimelineStatsVM(new WCProductTimeline { WorkCenterID = id, WorkCenter = repo.GetById<WorkCenter>(id) }, repo)
                        {
                            WorkCenterID = id
                        };
                        var pdt = new PlannedDtLog
                        {
                            Start = now,
                            PlannedDtID = repo.GetOne<PlannedDt>(x => x.Name.Equals("Product Change Over")).Id,
                            Notes = "WC Startup",
                            WorkCenterID = id
                        };
                        tlVm.CreateNewCurrent(now, pdt);
                        try
                        {
                            tlVm.repo.Save();
                        }
                        catch (Exception ex)
                        {
                            repo.InsertError(new AppError
                            {
                                ErrorDT = now,
                                ErrorMsg = ex.Message,
                                Source = "WCController - Initial setup"
                            });
                            repo.Save();
                        }
                    }
                    else
                    {
                        tlVm = new ProductTimelineStatsVM(tl, repo);
                    }
                    //db.Proxies = true;

                    var viewModel = new WCVM
                    {
                        CallLogs =
                            repo.Get<CallLog>(
                                cla =>
                                    cla.WorkCenterId == id &&
                                    ((cla.Call.DT && cla.ResolveDt == null) || (!cla.Call.DT && cla.ResponseDt == null))),
                        WorkCenter = repo.GetFirst<WorkCenter>(x => x.Id == id, includeProperties: "WorkCenterCalls"),
                        Employee = new Employee(),
                        //WorkCenterCalls = repo.GetAll<WorkCenterCall>(x => x.WorkCenterID = id),
                        Calls = repo.GetAll<Call>()
                    };
                    //db.Proxies = false;
                    var pid = viewModel.WorkCenter.ProductID;

                    ViewBag.PID = pid;
                    var prodName = pid != null ? repo.GetById<Product>(pid).Name : null;
                    ViewBag.ProductName = prodName ?? "Select Product";

                    //PopulateProductDD(id, pid);

                    viewModel.ProductTimelineStatsVm = tlVm; //SetOEEHeader(id, pid);

                    ViewBag.Title = "WC " + viewModel.WorkCenter.Name;
                    var context = new ApplicationDbContext();
                    var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                    var user = userManager.FindByName("WorkCenter" + viewModel.WorkCenter.Id);
                    if (user != null)
                    {
                        var identity = userManager.CreateIdentity(user, DefaultAuthenticationTypes.ApplicationCookie);
                        var authenticationManager = HttpContext.GetOwinContext().Authentication;
                        authenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = true }, identity);
                    }
                    ViewBag.ServerTime = DateTime.Now;
                    return View(viewModel);
                }
            }

        }

        //private ProductTimelineStatsVM SetOEEHeader(int workCenterId, int? pid = null)
        //{
            
        //    var oeeHeader = _cache.ReturnWCTL(workCenterId);
        //    // do not attempt to start another update if updating
        //    if (oeeHeader.Updating) return oeeHeader;
        //    var now = DateTime.UtcNow;
        //    if (now.Subtract(oeeHeader.LastUpdate).TotalMilliseconds < 10000) return oeeHeader;
        //    oeeHeader.Updating = true;
        //    oeeHeader.LastUpdate = now;

        //    try
        //    {
        //        var current =
        //            _repo.GetOne<WCProductTimeline>(x => x.WorkCenterID == workCenterId && x.Current,
        //                includeProperties: "ProductWCStatsHistory, WorkCenter, Product");

        //        // need to add some logic to handle if the above comes back with more than one record.
        //        oeeHeader.TL = current;
        //        //current.Current = true;
        //        if (current != null)
        //        {
        //            _repo.Get<Timesegment>(
        //                wc =>
        //                    wc.WCProductTimelineID == current.Id &&
        //                    ((wc.Start <= current.Start && (wc.Stop ?? now) > current.Start) ||
        //                     (wc.Start > current.Start && wc.Start < current.Stop)),
        //                includeProperties: "CycleSummary, CallLogs, PlannedDtLogs, Scraps");

        //            foreach (var ts in current.Timesegments)
        //            {
        //                if (ts.CycleSummaryID != null)
        //                {
        //                    ts.CycleSummary = _repo.GetById<CycleSummary>(ts.CycleSummaryID);
        //                }

        //                if (ts.Scraps != null)
        //                {
        //                    foreach (var s in ts.Scraps)
        //                    {
        //                        s.ScrapType = _repo.GetById<ScrapType>(s.ScrapTypeID);
        //                    }
        //                }

        //                if (ts.PlannedDtLogs != null)
        //                {
        //                    foreach (var p in ts.PlannedDtLogs)
        //                    {
        //                        p.PlannedDt = _repo.GetById<PlannedDt>(p.PlannedDtID);
        //                    }
        //                }
        //                if (ts.CallLogs != null)
        //                {
        //                    foreach (var c in ts.CallLogs)
        //                    {
        //                        c.Call = _repo.GetById<Call>(c.CallID);
        //                    }
        //                }
        //            }
        //            // this should not be set here.
        //            //oeeHeader.TL = current;

        //        }
        //        //db.Configuration.ProxyCreationEnabled = false;
        //        if (oeeHeader.TL != null)
        //        {
        //            OeeCache.CacheWCTL(oeeHeader);
        //            oeeHeader.repo = _repo;
        //            oeeHeader.SetValues(_repo.GetById<WorkCenter>(workCenterId).OEEStartTime, now);
        //            _repo = oeeHeader.repo;
        //            _repo.Update(oeeHeader.TL, User.Identity.Name);
        //            oeeHeader.LastUpdate = now;
        //            oeeHeader.Updating = false;
        //            _repo.Save();
        //        }

        //    }
        //    catch (Exception ex)
        //    {
        //        _repo.InsertError(new AppError
        //        {
        //            ErrorDT = DateTime.UtcNow,
        //            ErrorMsg = "WcId: " + workCenterId + " -- " + ex.Message,
        //            Source = oeeHeader.WCProduct + ": WCController - Update OEEHeader"
        //        });
        //        _repo.Save();
        //    }
        //    finally
        //    {
        //        oeeHeader.Updating = false;

Vistech.Andon.Web/Views/CallManagementCenter/CallManagementCenter.cshtml
@model ProAlert.Andon.Service.ViewModels.CMCVM

@*@{ Layout = ""; }
@Styles.Render("~/Content/css")*@
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<link href="~/Scripts/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<style>
    .b1 {
        background-color: red;
    }

    .b2 {
        background-color: white;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>CallLog</legend>
        <div id="CloseCallLogForm" title="Close Call Log"></div>

        <table id="CallLog">
            <tr>
                <th>Work Center</th>
                <th>Call</th>
                <th>Initiated</th>
                <th>Responded</th>
                <th>Resolved</th>
                <th></th>
            </tr>
            @foreach (var item in Model.CallLogs)
            {
                <tr>
                    <td>@item.WorkCenter.Name</td>
                    <td>@item.Call.Name</td>
                    <td title="@(item.DispInitiateDt((TimeZoneInfo)Session["tzi"]).ToShortDateString())">@(item.DispInitiateDt((TimeZoneInfo)Session["tzi"]))
                    </td>
                    <td title="@(item.ResponseDt.HasValue ? DateTime.Parse(item.DispResponseDt((TimeZoneInfo)Session["tzi"]).ToString()).ToShortDateString() : "")">@(item.ResponseDt.HasValue ? DateTime.Parse(item.DispResponseDt((TimeZoneInfo)Session["tzi"]).ToString()).ToLongTimeString() : "")
                    </td>
                    <td class="resdt" title="@(item.ResolveDt.HasValue ? DateTime.Parse(item.DispResolveDt((TimeZoneInfo)Session["tzi"]).ToString()).ToShortDateString() : "")">@(item.ResolveDt.HasValue ? DateTime.Parse(item.DispResolveDt((TimeZoneInfo)Session["tzi"]).ToString()).ToShortTimeString() : "")
                    </td>
                    <td>
                        @{
                if (item.ResolveDt == null)
                {
                            <input type="button" value="Sign-off" class="actCall" title="WC Down" id="@item.Id"/>
                }
                else
                {
                            <input type="button" value="Sign-off" class="actCall" id="@item.Id"/>
                }
                        }
                    </td>
                </tr>
            }
        </table>
        @Html.HiddenFor(model => model.Employee.Id)
    </fieldset>
    <input type="hidden" id="clid" />
    <div id="ajaxResult">result</div>

}
<script>

    $(document).ready(function () {
        $(document).tooltip();
        $("#CallLog tr").each(function () {
            var b = $(this).find(".resdt").attr("title");
            if (b === "")
                $(this).find(".actCall").css("background-color", "red");
        });
    });


    $.ajaxSetup({ cache: false });

    $("#CallLog").on('click', '.actCall', function () {
        $("#clid").val((this).id);
        $(".ui-dialog:has(#CloseCallLogForm)").remove();
        CloseCall(@Model.Employee.Id);
    });

    function CloseCall(empid) {
        var id = $("#clid").val();
        var url = '@Url.Action("CloseCallLogGet", "WC", new { calllogid = "_id", empid = "_empid" })';
        url = url.replace("_id", id);
        url = url.replace("_empid", empid);
        url = url.replace("amp;", "");
        $("#CloseCallLogForm").dialog({
            autoOpen: true,
            width: 600,
            resizable: false,
            title: 'Close Call Log Form',
            modal: true,
            position: { my: "center bottom", at: "center", of: window },
            open: function () {
                $(this).load(url);
            },
            buttons: {
                "Sign-off": function () {
                    CloseCallLogInfo();
                },
                "Later": function () {
                    LaterCallLog();
                }
            }
        });
    }
    //.next(".ui-widget-overlay").css("background", "#4682b4")
    function CloseCallLogInfo() {
        dlg = $("#CloseCallLogForm");
        $.ajax({
            url: '@Url.Action("CloseCallLog", "CallManagementCenter")',
            type: "POST",
            data: $("#cclTarget").serialize(),
            dataType: 'html',
            success: function (data) {
                if (data) {
                    $(dlg).dialog('close');
                    $("#CallLog").html(data);
                    $("#ajaxResult").hide().html('Record saved').fadeIn(300, function () {
                        var e = this;
                        setTimeout(function () { $(e).fadeOut(400); }, 2500);
                    });
                }
            },
            error: function (xhr) {
                if (xhr.status == 400)
                    dlg.html(xhr.responseText, xhr.status); /* display validation errors in edit dialog */
                else
                    displayError(xhr.responseText, xhr.status); /* display other errors in separate dialog */
            }
        });
    }

    function LaterCallLog() {
        var dlg = $("#CloseCallLogForm");
        $.ajax({
            url: '@Url.Action("LaterCallLog", "CallManagementCenter")',
            type: "POST",
            data: $("#cclTarget").serialize(),
            dataType: 'html',
            success: function (data) {
                if (data) {
                    $(dlg).dialog("close");
                    $("#ajaxResult").hide().html('Record saved').fadeIn(300, function () {
                        var e = this;
                        setTimeout(function () { $(e).fadeOut(400); }, 2500);
                    });
                }
            },
            error: function (xhr) {
                if (xhr.status == 400)
                    dlg.html(xhr.responseText, xhr.status);     /* display validation errors in edit dialog */
                else
                    displayError(xhr.responseText, xhr.status); /* display other errors in separate dialog */

            }
        });
    }

    function displayError(message, status) {
        var $dialog = $(message);
        $dialog
            .dialog({
                modal: true,
                title: status + ' Error',
                buttons: {
                    Ok: function () {
                        $(this).dialog("close");
                    }
                }
            });
        return false;
    };
</script>

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@