Vistech.Andon.Web/Controllers/ScrapController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Text;
using System.Transactions;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ProAlert.Andon.Service.Interfaces;
using ProAlert.Andon.Service.Models;
using ProAlert.Andon.Service.ViewModels;
using Vistech.Andon.Web.Models;

namespace Vistech.Andon.Web.Controllers
{
    //[InitializeSimpleMembership]
    [Authorize(Roles = "Admin, Tech, Maint, Super")]
    public class ScrapController : Controller
    {
        #region < Members >
        protected readonly IRepository _repo;
        #endregion
        //
        // GET: /Scrap/
        public ScrapController(IRepository repo)
        {
            _repo = repo;
        }

        public ActionResult Index(bool? SignOff)
        {
            var scraps = _repo.Get<Scrap>(s => (SignOff == true ? s.SignoffDT != null : s.SignoffDT == null), orderBy: s => s.OrderByDescending(o => o.Id),
                includeProperties: "WorkCenter, LastStage, RejectCode, ScrapType");
            return View(scraps.ToList());
        }

        public ActionResult Filtered(int? WorkCenterID, int? ScrapTypeID, bool? SignOff, int? EmployeeID, bool? Parent)
        {
            PopulateAdminDD();
            PopulateScrapTypeDD();
            PopulateWorkCenterDD();
            List<Scrap> vm;
            if (WorkCenterID == null)
            {
                if (ScrapTypeID == null)
                {
                    vm = _repo.Get<Scrap>(s => (SignOff == true ? s.SignoffDT != null : s.SignoffDT == null) &&
                                                      ((EmployeeID == null
                                                           ? s.EmployeeID != null
                                                           : s.EmployeeID == EmployeeID) || s.EmployeeID == null) &&
                                                      (Parent == true ? s.Allocated : !s.Allocated)
                        , orderBy: s => s.OrderByDescending(o => o.Id)
                        , includeProperties: "WorkCenter, Product, LastStage, RejectCode, ScrapType").ToList();
                    return View(vm);
                }
                vm = _repo.Get<Scrap>(s => s.ScrapType.Id == ScrapTypeID && (SignOff == true ? s.SignoffDT != null : s.SignoffDT == null) &&
                    ((EmployeeID == null ? s.EmployeeID != null : s.EmployeeID == EmployeeID) || s.EmployeeID == null) && (Parent == true ? s.Allocated : !s.Allocated)
                    , orderBy: s => s.OrderByDescending(o => o.Id)
                    , includeProperties: "WorkCenter, Product, LastStage, RejectCode, ScrapType").ToList();
                return View(vm);
            }
            if (ScrapTypeID == null)
            {
                vm = _repo.Get<Scrap>(s => s.WorkCenterID == WorkCenterID && (SignOff == true ? s.SignoffDT != null : s.SignoffDT == null) &&
                        ((EmployeeID == null ? s.EmployeeID != null : s.EmployeeID == EmployeeID) || s.EmployeeID == null) && (Parent == true ? s.Allocated : !s.Allocated)
                                                         , orderBy: s => s.OrderByDescending(o => o.Id)
                                                         , includeProperties: "WorkCenter, Product, LastStage, RejectCode, ScrapType").ToList();
                return View(vm);
            }
            vm = _repo.Get<Scrap>(s => s.ScrapType.Id == ScrapTypeID && (SignOff == true ? s.SignoffDT != null : s.SignoffDT == null) &&
                s.WorkCenterID == WorkCenterID &&
                    ((EmployeeID == null ? s.EmployeeID != null : s.EmployeeID == EmployeeID) || s.EmployeeID == null) && (Parent == true ? s.Allocated : !s.Allocated)
                                                     , orderBy: s => s.OrderByDescending(o => o.Id)
                                                     , includeProperties: "WorkCenter, Product, LastStage, RejectCode, ScrapType").ToList();
            return View(vm);
        }
        //
        // GET: /Scrap/Details/5

        public ActionResult Details(int id = 0)
        {
            Scrap scrap = _repo.Get<Scrap>(x => x.Id == id, includeProperties: "WorkCenter, Product, LastStage, RejectCode, ScrapType").SingleOrDefault();
            if (scrap == null)
            {
                return HttpNotFound();
            }
            return View(scrap);
        }

        //
        // GET: /Scrap/Create

        public ActionResult Create()
        {
            var vm = new ScrapVM { 
                Scrap = new Scrap(),
                WorkCenters = _repo.Get<WorkCenter>(orderBy: s => s.OrderBy(o => o.Name)),
                Products = _repo.Get<Product>(orderBy: s => s.OrderBy(o => o.Name)),
                LastStages = _repo.Get<LastStage>(orderBy: s => s.OrderBy(o => o.Name)),
                RejectCodes = _repo.Get<RejectCode>(orderBy: s => s.OrderBy(o => o.Name)),
                ScrapTypes = _repo.Get<ScrapType>(orderBy: s => s.OrderBy(o => o.Name))
            };

            return View(vm);
        }

        private void PopulateWorkCenterDD(object selectedWorkCenter = null)
        {
            var workcenterQuery = from wc in _repo.Get<WorkCenter>()
                orderby wc.Name
                select wc;
            ViewBag.WorkCenterID = new SelectList(workcenterQuery, "Id", "Name", selectedWorkCenter);
        }

        private void PopulateScrapTypeDD(object selectedScrapType = null)
        {
            var scraptypeQuery = from s in _repo.Get<ScrapType>()
                orderby s.Name
                select s;
            ViewBag.ScrapTypeID = new SelectList(scraptypeQuery, "Id", "Name", selectedScrapType);
        }

        private void PopulateAdminDD(object selectedAdmin = null)
        {
            var list = new List<emp>();
            try
            {

                using (var aContext = new ApplicationDbContext())
                {
                    var userStore = new UserStore<ApplicationUser>(aContext);
                    var userManager = new UserManager<ApplicationUser>(userStore);
                    var lUsers = (from u in userManager.Users
                                  select u).ToList();
                    foreach (var user in lUsers)
                    {
                        if (!userManager.IsInRole(user.Id, "Admin") && !userManager.IsInRole(user.Id, "Super")) continue;
                        var e = _repo.GetFirst<Employee>(x => x.LogIn.Equals(user.UserName));
                        if (e == null) continue;
                        list.Add(new emp
                        {
                            EmployeeID = e.Id,
                            FullName = e.FullName
                        });
                    }
                }
            }
            catch (Exception ex)
            {
                var ae = new AppError
                {
                    ErrorDT = DateTime.UtcNow,
                    ErrorMsg = ex.Message.ToString(),
                    Source = "ScrapController - PopulateAdminDD"
                };

                _repo.InsertError(ae);
                _repo.Save();
            }
            ViewBag.UserId = new SelectList(list, "EmployeeID", "FullName", selectedAdmin);
        }
        //
        // POST: /Scrap/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ScrapTypeID, ScrapCount, WorkCenterID, ProductID, RejectCodeID, LastStageID, Notes, DefectLocation, ScrapParentID")] Scrap scrap, 
            [Bind(Include="Id, Qty")] List<ScrapType> scraptypes)
        {
            if (ModelState.IsValid)
            {
                var name = User.Identity.Name;
                var user = _repo.GetFirst <Employee>(x => x.LogIn.Trim() == name.Trim());
                int? empId = null;
                if (user != null)
                    empId = user.Id;
                scrap.ScrapTypeID = _repo.GetFirst<ScrapType>(s => s.Default).Id;

                scrap.ScrapDT = DateTime.UtcNow;
                scrap.EmployeeID = empId;

                using (var trans = new TransactionScope())
                {
                    // create parent scrap record
                    // get parentID
                    _repo.Create(scrap, name);
                    _repo.Save();
                    var id = scrap.Id;

                    foreach (var item in scraptypes.Where(x => x.Qty != null || x.Qty > 0))
                    {
                        var child = new Scrap
                        {
                            WorkCenterID = scrap.WorkCenterID,
                            ProductID = scrap.ProductID,
                            LastStageID = scrap.LastStageID,
                            RejectCodeID = scrap.RejectCodeID,
                            ScrapTypeID = item.Id,
                            ScrapCount = item.Qty ?? 0,
                            ScrapDT = scrap.ScrapDT,
                            EmployeeID = scrap.EmployeeID,
                            DefectLocation = scrap.DefectLocation,
                            ScrapParentID = id
                        };
                        _repo.Create(child, name);
                        _repo.Save();
                    }
                    trans.Complete();
                }

                return RedirectToAction("Filtered", new { WorkCenterID = scrap.WorkCenterID });
            }
            var vm = new ScrapVM
            {
                Scrap = scrap,
                WorkCenters = _repo.GetAll<WorkCenter>(orderBy: s => s.OrderBy(o => o.Name)),
                Products = _repo.GetAll<Product>(orderBy: s => s.OrderBy(o => o.Name)),
                LastStages = _repo.GetAll<LastStage>(orderBy: s => s.OrderBy(o => o.Name)),
                RejectCodes = _repo.GetAll<RejectCode>(orderBy: s => s.OrderBy(o => o.Name)),

Vistech.Andon.Web/Views/Scrap/Create.cshtml
@using System.Web.Mvc.Html
@using Vistech.Andon.Web.helpers
@model ProAlert.Andon.Service.ViewModels.ScrapVM

@{
    ViewBag.Title = "Create Scrap";
}
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>

<style>
    .red-cell {
        background: red;
    }
    .qty {
        width: 40px;
    }
</style>
<script>
    $(document).ready(function () {
        $('.loc').click(function () {
            $(this).toggleClass("red-cell");
            createString();
        });

        function createString() {
            var list = "";
            $('.loc').each(function () {
                if ($(this).hasClass("red-cell")) {
                    list = list + $(this).attr('id') + ',';
                }
            });
            $("#Scrap_DefectLocation").val(list);
            $("#Scrap_Notes").focus();
        }

        $("#Scrap_DefectLocation").click(function () {
            alert("Do not attempt to edit this field by hand.  Use picture to locate defects.");
            createString();
        });

        window.onload = function () {
            var arr = $("#Scrap_DefectLocation").val().split(',');
            $.each(arr, function (index, value) {
                $('.loc').each(function () {
                    if ($(this).attr('id') == value.trim()) {
                        $(this).toggleClass('red-cell');
                    }
                });
            });
        }
        
        function displayError(message, status) {
            var $dialog = $(message);
            $dialog
                .dialog({
                    modal: true,
                    title: status + ' Error',
                    buttons: {
                        Ok: function () {
                            $(this).dialog("close");
                        }
                    }
                });
            return false;
        };

        $(".qty").change(function () {
            var oVal = $("#Scrap_ScrapCount").val();
            var rem = 0;
            if (!$.isNumeric($(this).val())) {
                $(this).val("");
                return false;
            }
            var total = 0;
            jQuery(".qty").each(function () {
                if ($.isNumeric($(this).val())) {
                    total += parseFloat($(this).val());
                }
            });
            if (oVal - total < 0) {
                alert("too much");
                total = total - parseFloat($(this).val());
                //alert(oVal - total);
                $(this).val(oVal - total);
                rem = 0;
            } else {
                rem = oVal - total;
            }
            var myLabel = document.getElementById("lbRemain");
            myLabel.innerText = "Remaining: " + rem;
        });
    });
</script>
<h2>Create Scrap</h2>

@using (Html.BeginForm("Create", "Scrap", FormMethod.Post, new { id = "csTarget" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Scrap</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Scrap.WorkCenterID, "WorkCenter")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Scrap.WorkCenterID, new SelectList(Model.WorkCenters, "Id", "Name"), "<-- Select WC -->")
            @Html.ValidationMessageFor(model => model.Scrap.WorkCenterID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Scrap.ProductID, "Product")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Scrap.ProductID, new SelectList(Model.Products, "Id", "Name"), "<-- Select Prod -->")
            @Html.ValidationMessageFor(model => model.Scrap.ProductID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Scrap.LastStageID, "Last Stage")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Scrap.LastStageID, new SelectList(Model.LastStages, "Id", "Name"), "<-- Select -->")
            @Html.ValidationMessageFor(model => model.Scrap.LastStageID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Scrap.RejectCodeID, "Reject Code")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Scrap.RejectCodeID, new SelectList(Model.RejectCodes, "Id", "Name"), "<-- Select -->")
            @Html.ValidationMessageFor(model => model.Scrap.RejectCodeID)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Scrap.ScrapCount)
            <label id="lbRemain" style="padding-left: 50px"></label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Scrap.ScrapCount)
            @Html.ValidationMessageFor(model => model.Scrap.ScrapCount)
        </div>
        <div class="editor-label" style="padding-left: 130px">
            <table id="distScrap">
                @Html.EditorFor(model => model.ScrapTypes)
            </table>
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Scrap.Notes)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Scrap.Notes)
            @Html.ValidationMessageFor(model => model.Scrap.Notes)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Scrap.DefectLocation)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Scrap.DefectLocation)
            @Html.ValidationMessageFor(model => model.Scrap.DefectLocation)
        </div>
        <div class="display-label">
            <table id="defectLocator" style="width:320px; height:240px; padding:0; font-size:2px;" background="@Html.ImageString(Model.Scrap.Product.Image)">
                @{
                    var cnt = 0;
                    for (var i = 1; i <= 20; i++)
                    {
                        @:<tr>
                       for (var j = 0; j <= 19; j++)
                       {
                            cnt += 1;
                            @:<td class="loc" id="@cnt"></td>
                       }
                       @:</tr>
                   }
                }
            </table>
        </div>
        <div style="float: left; clear: both">
            <input id="btn" type="submit" value="Create" />
        </div>
        <div id="divPin" title="Collect Pin"></div>
        @Html.HiddenFor(model => model.Scrap.EmployeeID)
    </fieldset>
}
<div id="ajaxResult">result</div>
<div>
    @Html.ActionLink("Back to List", "Filtered")
</div>

<style type="text/css">
    div.btn-Panel {
        display: none;
    }
</style>

<script>
    $("#Scrap_ProductID").on('change', function () {
        loadImage(this.value);
    });

    function loadImage(id) {
        $.ajax({
            url: '@Url.Action("LoadImage", "Scrap")',
            data: { prodid: id },
            success: function (data) {
                if (data) {
                    $("#defectLocator").attr('background', data.img);
                }
            },
            error: function (xhr) {
                if (xhr.status == 400)
                    body.html(xhr.responseText, xhr.status); /* display validation errors in edit dialog */
                else
                    displayError(xhr.responseText, xhr.status); /* display other errors in separate dialog */

            }
        });
    }

@*    $("#Scrap_WorkCenterID").on('change', function() {
        // post back to get filtered list of Products by ProductWorkCenterStat table.
        $.ajax({
            url: '@Url.Action("")'
        })
    });*@

    function displayError(message, status) {
        var $dialog = $(message);
        $dialog
            .dialog({
                modal: true,
                title: status + ' Error',
                buttons: {
                    Ok: function () {
                        $(this).dialog("close");
                    }
                }
            });
        return false;
    };

</script>
@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Vistech.Andon.Web/Views/Scrap/Delete.cshtml
@model ProAlert.Andon.Service.Models.Scrap

@{
    ViewBag.Title = "Delete Scrap";
}

<h2>Delete Scrap</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Scrap</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Id)
    </div>
    <div class="display-field">
        @{
            var id = Model.Id.ToString();
            if (id.Length > 2)
            {
                id = id.Substring(id.Length - 2);
            }
        }
        @Html.DisplayFor(modelItem => id)    
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.WorkCenter.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WorkCenter.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Product.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Product.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.LastStage.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastStage.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.RejectCode.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RejectCode.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ScrapType.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ScrapType.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ScrapDT)
    </div>
    <div class="display-field">
        @{ var d = Model.DispScrapDt((TimeZoneInfo)Session["tzi"]); }
        @Html.DisplayFor(modelItem => d)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ScrapCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ScrapCount)
    </div>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" />
        |
        @Html.ActionLink("Back to List", "Filtered", new { WorkCenterID = Model.WorkCenterID })
    </p>
}

Vistech.Andon.Web/Views/Scrap/Details.cshtml
@using Vistech.Andon.Web.helpers
@model ProAlert.Andon.Service.Models.Scrap

@{
    ViewBag.Title = "Scrap Details";
}
<style>
    .red-cell {
        background: red;
    }
</style>
<script>
    $(document).ready(function () {
        $('.loc').click(function () {
            $(this).toggleClass("red-cell");
            createString();
        });

        function createString() {
            var list = "";
            $('.loc').each(function () {
                if ($(this).hasClass("red-cell")) {
                    list = list + $(this).attr('id') + ',';
                }
            });
            $("#DefectLocation").val(list);
            $("#Notes").focus();
        }

        $("#DefectLocation").click(function () {
            alert("Do not attempt to edit this field by hand.  Use picture to locate defects.");
            createString();
        });

        window.onload = function () {
            var arr = $("#DefectLocation").val().split(',');
            $.each(arr, function (index, value) {
                $('.loc').each(function () {
                    if ($(this).attr('id') == value.trim()) {
                        $(this).toggleClass('red-cell');
                    }
                });
            });
            $("#DefectLocation").attr("disabled", true);
        }

        function displayError(message, status) {
            var $dialog = $(message);
            $dialog
                .dialog({
                    modal: true,
                    title: status + ' Error',
                    buttons: {
                        Ok: function () {
                            $(this).dialog("close");
                        }
                    }
                });
            return false;
        };
    });
</script>

<h2>Scrap Details</h2>

<fieldset>
    <legend>Scrap</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Id)
    </div>
    <div class="display-field">
        @{
            var id = Model.Id.ToString();
            if (id.Length > 2)
            {
                id = id.Substring(id.Length - 2);
            }
        }
        @Html.DisplayFor(modelItem => id)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.WorkCenter.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WorkCenter.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Product.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Product.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.LastStage.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastStage.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.RejectCode.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RejectCode.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ScrapType.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ScrapType.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ScrapDT)
    </div>
    <div class="display-field">
        @{ var d = Model.DispScrapDt((TimeZoneInfo)Session["tzi"]); }
        @Html.DisplayFor(modelItem => d)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ScrapCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ScrapCount)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.DefectLocation)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(model => model.DefectLocation)
    </div>

        <div class="display-label">
            <table id="defectLocator" style="width:320px; height:240px; padding:0; font-size:2px;" background="@Html.ImageString(Model.Product.Image)">
                @{
               for (int i = 1; i <= 20; i++)
               {
                    @:<tr>
                    for (int j = 0; j <= 19; j++)
                    {
                        @: <td class="loc" id="@i@j"></td>
                    }

                    @:</tr>
                }
                }
            </table>
        </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Filtered", new { WorkCenterID = Model.WorkCenterID })
</p>

Vistech.Andon.Web/Views/Scrap/Filtered.cshtml
@model IEnumerable<ProAlert.Andon.Service.Models.Scrap>

@{
    ViewBag.Title = "Scrap";
}

<h2>Scrap</h2>
@using (Html.BeginForm("Filtered", "Scrap", FormMethod.Get))
{
    <table>
        <tr>
            <td>@Html.DropDownList("UserId", "<-- Select User -->")</td>
            <td>@Html.DropDownList("WorkCenterID", "<--select Work Center-->")</td>
            <td>@Html.DropDownList("ScrapTypeID", "<--select Scrap Type-->")</td>            
            <td>@Html.CheckBox("SignOff") Signed Off</td>
            <td>@Html.CheckBox("Parent") Original Entry</td>
            <td>
                <input type="submit" value="Filter" />
            </td>
        </tr>
    </table>
}
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Allocated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkCenter.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastStage.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RejectCode.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScrapType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScrapDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScrapCount)
        </th>
        <th>QC Tech
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td title="@item.ScrapParentID">
                @Html.DisplayFor(modelItem => item.Allocated)
            </td>
            <td>
                @{
                    var id = item.Id.ToString();
                    if (id.Length > 2)
                    {
                        id = id.Substring(id.Length - 2);
                    }
                }
                @Html.DisplayFor(modelItem => id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkCenter.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastStage.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RejectCode.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScrapType.Name)
            </td>
            <td>
                @{ var d = item.DispScrapDt((TimeZoneInfo) Session["tzi"]); }
                @Html.DisplayFor(modelItem => d)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScrapCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.FullName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
                @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.Id})
            </td>
        </tr>
    }

</table>

Vistech.Andon.Web/Views/Scrap/Index.cshtml
@model IEnumerable<ProAlert.Andon.Service.Models.Scrap>

@{
    ViewBag.Title = "Scrap Index";
}

<h2>Scrap Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Scrap", FormMethod.Get))
{
    @Html.CheckBox("SignOff") @:Signed Off
    <input type="submit" value="Filter" />
}
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkCenter.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastStage.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RejectCode.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScrapType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScrapDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScrapCount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    var id = item.Id.ToString();
                    if (id.Length > 2)
                    {
                        id = id.Substring(id.Length - 2);
                    }
                }
                @Html.DisplayFor(modelItem => id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkCenter.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastStage.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RejectCode.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScrapType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScrapDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ScrapCount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>