Vistech.Andon.Web/Controllers/IssueController.cs
using System;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;
using ProAlert.Andon.Service.Interfaces;
using ProAlert.Andon.Service.Models;
using ProAlert.Andon.Service.ViewModels;

namespace Vistech.Andon.Web.Controllers
{
    //[InitializeSimpleMembership]
    [Authorize(Roles = "Admin")]
    public class IssueController : Controller
    {
        private IRepository _repo;

        public IssueController(IRepository repo)
        {
            _repo = repo;
        }
        //
        // GET: /Issue/

        public ActionResult Index()
        {
            var issues = _repo.GetAll<Issue>(includeProperties: "SubCategory");
            return View(issues.ToList());
        }

        //
        // GET: /Issue/Details/5

        public ActionResult Details(int id = 0)
        {
            var issue = _repo.GetOne<Issue>(x => x.Id == id, includeProperties: "SubCategory");
            if (issue == null)
            {
                return HttpNotFound();
            }
            return View(issue);
        }

        //
        // GET: /Issue/Create

        public ActionResult Create()
        {
            var vm = new IssueVM();

            return View(vm);
        }
        //
        // POST: /Issue/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IssueVM vm)
        {
            if (_repo.Get<Issue>(x => x.Name.Equals(vm.Name)).Any())
                ModelState.AddModelError("Name", "Already exists");
            if (ModelState.IsValid)
            {
                var nI = new Issue {Name = vm.Name, Description = vm.Description};
                _repo.Create(nI, User.Identity.Name);
                _repo.Save();
                return RedirectToAction("Index");
            }

            return View(vm);
        }

        //
        // GET: /Issue/Edit/5

        public ActionResult Edit(int id = 0)
        {
            var issue = _repo.GetById<Issue>(id);
            if (issue == null)
            {
                return HttpNotFound();
            }
            var vm = new IssueVM { Id = issue.Id, Name = issue.Name, Description = issue.Description};
            return View(vm);
        }

        //
        // POST: /Issue/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IssueVM vm)
        {
            if (ModelState.IsValid)
            {
                var rowToUpdate = _repo.GetById<Issue>(vm.Id);
                rowToUpdate.Description = vm.Description;

                try
                {
                    _repo.Update(rowToUpdate, User.Identity.Name);
                    _repo.Save();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    _repo.InsertError(new AppError
                    {
                        ErrorDT = DateTime.UtcNow,
                        ErrorMsg = ex.Message,
                        Source = "Issue Controller : Edit"
                    });
                    _repo.Save();
                }
            }
            return View(vm);
        }

        //
        // GET: /Issue/Delete/5

        public ActionResult Delete(int id = 0)
        {
            var issue = _repo.GetById<Issue>(id); //<Issue>(includeProperties:"SubCategory");
            ViewBag.Msg = _repo.Get<CallLog>(x => x.IssueID == id).Any() ? "Cannot delete." : "Are you sure you want to delete?";
            if (issue == null)
            {
                return HttpNotFound();
            }
 
            return View(issue);
        }

        //
        // POST: /Issue/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                _repo.Delete<Issue>(id);
                _repo.Save();
            }
            catch (Exception ex)
            {
                if (ex.Message.StartsWith("Violation of UNIQUE KEY constraint"))
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    ModelState.AddModelError("Name", "You cannot delete related data.");
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult SubCategoryCreate()
        {
            if (Request != null && Request.IsAjaxRequest())
                return PartialView("_SubCategoryCreate", new SubCategory());

            return View("_SubCategoryCreate", new SubCategory());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult SubCategoryCreate(SubCategory model)
        {
            var statusCode = 0;
            var errorMsg = string.Empty;
            StringBuilder errorMessage = null;
            if (!ModelState.IsValid)
            {
                if (Request.IsAjaxRequest())
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_SubCategoryCreate", model);
                }
                return PartialView("_SubCategoryCreate", model);
            }
            try
            {
                _repo.Create(model, User.Identity.Name);
                _repo.Save();
            }
            catch (Exception exp)
            {
                errorMessage = new StringBuilder(200);
                errorMessage.AppendFormat(
                    "<div class=\"validation-summary-errors\" title\"Server Error\">{0}</div>",
                    exp.GetBaseException().Message);
                statusCode = (int)HttpStatusCode.InternalServerError; // = 500
            }

            if (Request.IsAjaxRequest())
            {
                if (statusCode > 0)
                {
                    Response.StatusCode = statusCode;
                    return Content(errorMessage.ToString());
                }
                TempData["message"] = "Subcategory was added.";
                var id = _repo.Get<SubCategory>().Last().Id;
                return Json(new { sl = new SelectList(_repo.GetAll<SubCategory>(), "Id", "Name"), idx = id }, JsonRequestBehavior.AllowGet);
            }
            return RedirectToAction("Create");
        }
    }
}

Vistech.Andon.Web/Views/Issue/Create.cshtml
@model ProAlert.Andon.Service.ViewModels.IssueVM

@{
    ViewBag.Title = "Create Issue";
}
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.11.4.js"></script>
<h2>Create an Issue</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Issue</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

@*        <div class="editor-label">
            @Html.LabelFor(model => model.Material)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Material)
            @Html.ValidationMessageFor(model => model.Material)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Manufacturing)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Manufacturing)
            @Html.ValidationMessageFor(model => model.Manufacturing)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rework)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rework)
            @Html.ValidationMessageFor(model => model.Rework)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DT)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DT)
            @Html.ValidationMessageFor(model => model.DT)
        </div>*@

        @*<div class="editor-label">
            @Html.LabelFor(model => model.Issue.SubCategoryID, "SubCategory")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Issue.SubCategoryID, new SelectList(Model.SubCategories, "Id", "Name"), "<-- Select Subcategory -->")
            <button id="AddSubCategory">Add Subcategory</button>
            @Html.ValidationMessageFor(model => model.Issue.SubCategoryID)
        </div>*@
        
        @*<div id="AddSubCategoryForm" title="Add Subcategory"></div>*@
        <div style="float: left; clear: both">
            <input type="submit" value="Create" />
        </div>
        
        <input type="hidden" name="Sub" id="Sub" value=""/>
    </fieldset>
}

<div id="ajaxResult">result</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*<style type="text/css">
    div.btn-Panel {
        display: none;
    }
</style>*@

@*<script>

    $('#AddSubCategory').on('click', function () {
        $("#AddSubCategoryForm").dialog("open");
        return false;
    });

    $("#AddSubCategoryForm").dialog({
        autoOpen: false,
        width: 400,
        resizable: false,
        title: 'Add Subcategory Form',
        modal: true,
        open: function () {
            $(this).load('@Url.Action("SubCategoryCreate")');
        },
        buttons: {
            "Add Subcategory": function () {
                addSubCategoryInfo();
            },
            Cancel: function () {
                $(this).dialog("close");
            }
        }
    });

    function addSubCategoryInfo() {
        var dlg = $("#AddSubCategoryForm");
        $.ajax({
            url: '@Url.Action("SubCategoryCreate", "Issue")',
            type: "POST",
            data: $("#subTarget").serialize(),
            success: function (data) {
                if (data) {
                    var subDDL = $("#Issue_SubCategoryID");
                    subDDL.empty();
                    $.each(data.sl, function (i, obj) {
                        subDDL.append($('<option/>').val(obj.Value).text(obj.Text)).change();
                    });
                    subDDL.val(data.idx);
                    dlg.dialog("close");
                    $("#ajaxResult").hide().html('Record saved').fadeIn(300, function () {
                        var e = this;
                        setTimeout(function () { $(e).fadeOut(400); }, 2500);
                    });
                }
            }
        });

    }
</script>*@
@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Vistech.Andon.Web/Views/Issue/Delete.cshtml
@model ProAlert.Andon.Service.Models.Issue

@{
    ViewBag.Title = "Delete Issue";
}

<h2>Delete Issue</h2>

<h3>@ViewBag.Msg</h3>
<fieldset>
    <legend>Issue</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        @if (!ViewBag.Msg.Equals("Cannot delete."))
        {
            var pipe = "|";
            <input type="submit" value="Delete" /> @pipe
        }
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Vistech.Andon.Web/Views/Issue/Details.cshtml
@model ProAlert.Andon.Service.Models.Issue

@{
    ViewBag.Title = "Issue Details";
}

<h2>Issue Details</h2>

<fieldset>
    <legend>Issue</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

@*    <div class="display-label">
        @Html.DisplayNameFor(model => model.Material)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Material)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Manufacturing)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Manufacturing)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Rework)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rework)
    </div>
    
    <div class="display-label">
        @Html.DisplayNameFor(model => model.DT)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DT)
    </div>*@

    @*<div class="display-label">
        @Html.DisplayNameFor(model => model.SubCategory.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SubCategory.Name)
    </div>*@
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Vistech.Andon.Web/Views/Issue/Edit.cshtml
@model ProAlert.Andon.Service.ViewModels.IssueVM

@{
    ViewBag.Title = "Edit Issue";
}

<h2>Edit Issue</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Issue</legend>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Name)
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

@*        <div class="editor-label">
            @Html.LabelFor(model => model.Material)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Material)
            @Html.ValidationMessageFor(model => model.Material)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Manufacturing)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Manufacturing)
            @Html.ValidationMessageFor(model => model.Manufacturing)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rework)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rework)
            @Html.ValidationMessageFor(model => model.Rework)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DT)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DT)
            @Html.ValidationMessageFor(model => model.DT)
        </div>*@

        @*<div class="editor-label">
            @Html.LabelFor(model => model.Issue.SubCategoryID, "Sub Category")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Issue.SubCategoryID, new SelectList(Model.SubCategories, "Id", "Name"), "<-- Select Subcategory -->")
            @Html.ValidationMessageFor(model => model.Issue.SubCategoryID)
        </div>*@

        <div style="float: left; clear: both">
            <input type="submit" value="Save" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vistech.Andon.Web/Views/Issue/Index.cshtml
@model IEnumerable<ProAlert.Andon.Service.Models.Issue>

<style>
    th {
        padding: 5px;
    }
</style>
@{
    ViewBag.Title = "Issues Index";
}

<h2>Issues Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
@*        <th>
        @Html.DisplayNameFor(model => model.Material)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Manufacturing)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Rework)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.DT)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.SubCategory.Name)
    </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
@*        <td>
        @Html.DisplayFor(modelItem => item.Material)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Manufacturing)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Rework)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DT)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SubCategory.Name)
    </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>